### ISSUE TITLE
consistency between s3dRenderScene, s3dRenderOi, s3dRenderSceneAndDepth

### ISSUE THREAD

**Issue by ydnality** [ydnality/Scene3D#9]

**Comment by wandell** [comment]
Can you put an example lens file into the repository?

I read through and ran several scripts.    I can see various ways I can help.

Brian

**Comment by ydnality** [comment]
I've added dgauss.50mm.dat in  data/pbrtScenes/

Thanks!

-Andy

**Comment by wandell** [comment]
We are developing a set of scripts and relationship between the data files and rendering scripts that supercede this problem.  We are on our way.
